import React from 'react';
import { Timeline, Typography, Tag, Space, Avatar } from 'antd';
import { 
  GithubOutlined, 
  CheckCircleOutlined,
  SyncOutlined,
  PullRequestOutlined,
  CloseCircleOutlined
} from '@ant-design/icons';
import GlassCard from '../components/GlassCard';

const { Title, Text, Link } = Typography;

const PullRequests = () => {
  return (
    <div className="prs-container">
      <div style={{ marginBottom: 32 }}>
        <Title level={2} style={{ color: '#fff', margin: 0 }}>Pull Requests</Title>
        <Text style={{ color: 'var(--text-secondary)' }}>
          Track the status of PRs generated by the AI system.
        </Text>
      </div>

      <GlassCard>
        <Timeline mode="alternate" style={{ marginTop: '24px' }}>
          
          <Timeline.Item color="green" dot={<CheckCircleOutlined style={{ fontSize: '18px' }} />}>
            <GlassCard size="small" style={{ textAlign: 'left' }}>
              <Space direction="vertical" style={{ width: '100%' }}>
                <div style={{ display: 'flex', justifyContent: 'space-between' }}>
                  <Text strong style={{ color: '#fff', fontSize: '16px' }}>Merged: Add rate limiting to public APIs</Text>
                  <Tag color="success">Merged</Tag>
                </div>
                <Text type="secondary">Generated by AI, reviewed by <Avatar size="small" src="https://api.dicebear.com/7.x/avataaars/svg?seed=Felix" /> Alex</Text>
                <Link href="#" target="_blank"><GithubOutlined /> view on GitHub (#102)</Link>
              </Space>
            </GlassCard>
          </Timeline.Item>

          <Timeline.Item color="blue" dot={<SyncOutlined spin style={{ fontSize: '18px' }} />}>
            <GlassCard size="small" style={{ textAlign: 'left' }}>
              <Space direction="vertical" style={{ width: '100%' }}>
                <div style={{ display: 'flex', justifyContent: 'space-between' }}>
                  <Text strong style={{ color: '#fff', fontSize: '16px' }}>Open: Fix authentication token expiration bug</Text>
                  <Tag color="processing">Open</Tag>
                </div>
                <Text type="secondary">Generated 5 minutes ago. Waiting for CI/CD checks.</Text>
                <Link href="#" target="_blank"><GithubOutlined /> view on GitHub (#105)</Link>
              </Space>
            </GlassCard>
          </Timeline.Item>

          <Timeline.Item color="gray" dot={<PullRequestOutlined style={{ fontSize: '18px' }} />}>
            <GlassCard size="small" style={{ textAlign: 'left' }}>
              <Space direction="vertical" style={{ width: '100%' }}>
                <div style={{ display: 'flex', justifyContent: 'space-between' }}>
                  <Text strong style={{ color: '#fff', fontSize: '16px' }}>Draft: Upgrade AntD to v5</Text>
                  <Tag color="default">Draft</Tag>
                </div>
                <Text type="secondary">AI needs additional context. Check review logs.</Text>
                <Link href="#" target="_blank"><GithubOutlined /> view on GitHub (#106)</Link>
              </Space>
            </GlassCard>
          </Timeline.Item>

          <Timeline.Item color="red" dot={<CloseCircleOutlined style={{ fontSize: '18px' }} />}>
            <GlassCard size="small" style={{ textAlign: 'left' }}>
              <Space direction="vertical" style={{ width: '100%' }}>
                <div style={{ display: 'flex', justifyContent: 'space-between' }}>
                  <Text strong style={{ color: '#fff', fontSize: '16px' }}>Closed: Refactor webhook handlers</Text>
                  <Tag color="error">Closed</Tag>
                </div>
                <Text type="secondary">Closed by user. Overlapping PR detected.</Text>
                <Link href="#" target="_blank"><GithubOutlined /> view on GitHub (#101)</Link>
              </Space>
            </GlassCard>
          </Timeline.Item>

        </Timeline>
      </GlassCard>
    </div>
  );
};

export default PullRequests;
